name: 'Build docker images'
description: 'Build docker images and push it to AWS ECR>.'
inputs:
  ecr_url:
    description: 'AWS ECR URL'
    required: true
  aws_iam_role:
    description: ''
    required: true
  aws_region:
    default: us-east-1
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: ${{ inputs.aws_iam_role }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      shell: bash
      env:
        IMAGE: ${{ inputs.ecr_url }}
      run: |
        docker compose -f docker-compose.build.yaml build
        docker compose -f docker-compose.build.yaml push
