"""Criando tabelas no banco de dados

Revision ID: 9873e88259a2
Revises: c38378ee6284
Create Date: 2024-01-16 19:36:27.246734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9873e88259a2'
down_revision = 'c38378ee6284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
