"""Criando tabelas no banco de dados

Revision ID: c38378ee6284
Revises: 
Create Date: 2024-01-16 18:56:15.806103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38378ee6284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_sigla', sa.String(length=20), nullable=True),
    sa.Column('tx_nome', sa.String(length=200), nullable=True),
    sa.Column('nu_worker', sa.Integer(), server_default='1', nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nu_codigo', sa.Integer(), nullable=True),
    sa.Column('tx_nome', sa.String(length=100), nullable=True),
    sa.Column('tx_link', sa.String(length=100), nullable=True),
    sa.Column('tx_icon', sa.String(length=100), nullable=True),
    sa.Column('nu_ordem', sa.Integer(), server_default='1', nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_id'), 'menu', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('nu_cpf', sa.String(length=11), nullable=False),
    sa.Column('tx_nome', sa.String(length=300), nullable=True),
    sa.Column('tx_senha', sa.String(length=300), nullable=True),
    sa.Column('tx_email', sa.String(length=300), nullable=True),
    sa.Column('tx_foto', sa.Text(), nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('bo_worker', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('dt_inclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('nu_cpf')
    )
    op.create_index(op.f('ix_usuario_nu_cpf'), 'usuario', ['nu_cpf'], unique=False)
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_nome', sa.String(length=200), nullable=True),
    sa.Column('tx_finalidade', sa.String(length=1000), nullable=True),
    sa.Column('bo_superuser', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('bo_delegar', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('constante_virtual', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_id'), 'perfil', ['id'], unique=False)
    op.create_table('automacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('tx_nome', sa.String(length=200), nullable=True),
    sa.Column('tx_descricao', sa.String(length=200), nullable=True),
    sa.Column('tx_constante_virtual', sa.String(length=100), nullable=True),
    sa.Column('nu_qtd_tarefa', sa.Integer(), server_default='1', nullable=True),
    sa.Column('nu_qtd_download', sa.Integer(), server_default='1', nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.Column('dt_inclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_automacao_cliente'),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_automacao_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automacao_id'), 'automacao', ['id'], unique=False)
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automacao_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('historico_id', sa.Integer(), nullable=True),
    sa.Column('tx_nome', sa.String(length=200), nullable=True),
    sa.Column('tx_situacao', sa.String(length=200), nullable=True),
    sa.Column('bo_agendada', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('bo_execucao', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('dt_inclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dt_alteracao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('bo_email', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('json_agendamento', sa.Text(), nullable=True),
    sa.Column('tx_assunto_inicia', sa.String(length=200), nullable=True),
    sa.Column('tx_corpo_email_inicia', sa.Text(), nullable=True),
    sa.Column('tx_assunto_finaliza', sa.String(length=200), nullable=True),
    sa.Column('tx_corpo_email_finaliza', sa.Text(), nullable=True),
    sa.Column('tx_nome_script', sa.String(length=300), nullable=True),
    sa.Column('nu_prioridade', sa.Integer(), server_default='1', nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.Column('tx_constante_virtual', sa.String(length=100), nullable=True),
    sa.Column('anexo_script_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['automacao_id'], ['automacao.id'], name='fk_tarefa_automacao'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_tarefa_cliente'),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_tarefa_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_id'), 'tarefa', ['id'], unique=False)
    op.create_table('tarefa_historico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('automacao_id', sa.Integer(), nullable=True),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('dt_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dt_fim', sa.DateTime(), nullable=True),
    sa.Column('bo_status_code', sa.Integer(), nullable=True),
    sa.Column('tx_ip_execucao', sa.String(length=20), nullable=True),
    sa.Column('tx_resumo', sa.Text(), nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['automacao_id'], ['automacao.id'], name='fk_tarefahistorico_automacao'),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_tarefahistorico_usuario'),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], name='fk_tarefahistorico_tarefa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_historico_id'), 'tarefa_historico', ['id'], unique=False)
    op.create_table('anexo_script',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('tx_nome', sa.String(length=200), nullable=True),
    sa.Column('tx_extensao', sa.String(length=50), nullable=True),
    sa.Column('tx_tipo', sa.String(length=50), nullable=True),
    sa.Column('nu_tamanho', sa.Float(), nullable=True),
    sa.Column('nu_arquivo', sa.Integer(), nullable=True),
    sa.Column('nu_versao', sa.Integer(), nullable=True),
    sa.Column('dt_inclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dt_download', sa.DateTime(), nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], name='fk_tarefa_anexo_script'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexo_script_id'), 'anexo_script', ['id'], unique=False)
    op.create_table('cofre_senha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tx_nome', sa.String(length=300), nullable=True),
    sa.Column('tx_usuario', sa.String(length=50), nullable=True),
    sa.Column('tx_senha', sa.String(length=300), nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('dt_inclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_cofre_senha_cliente'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cofre_senha_id'), 'cofre_senha', ['id'], unique=False)
    op.create_table('controle_execucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('tx_descricao', sa.String(length=300), nullable=True),
    sa.Column('dt_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], name='fk_controle_execucao_tarefa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controle_execucao_id'), 'controle_execucao', ['id'], unique=False)
    op.create_table('dado_negocial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historico_tarefa_id', sa.Integer(), nullable=True),
    sa.Column('tx_descricao', sa.String(length=300), nullable=True),
    sa.Column('dt_inicio', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dt_fim', sa.DateTime(), nullable=True),
    sa.Column('tx_status', sa.String(length=50), nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['historico_tarefa_id'], ['tarefa_historico.id'], name='fk_dadosnegocial_historicotarefa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dado_negocial_id'), 'dado_negocial', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historico_tarefa_id', sa.Integer(), nullable=True),
    sa.Column('dt_inclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tx_status', sa.String(length=50), nullable=True),
    sa.Column('tx_descricao', sa.Text(), nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['historico_tarefa_id'], ['tarefa_historico.id'], name='fk_logs_historicotarefa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('perfil_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_perfilmenu_cliente'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], name='fk_perfilmenu_menu'),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], name='fk_perfilmenu_perfil'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_menu_id'), 'perfil_menu', ['id'], unique=False)
    op.create_table('perfil_tarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tarefa_id', sa.Integer(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], name='fk_perfiltarefa_perfil'),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], name='fk_perfiltarefa_tarefa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_tarefa_id'), 'perfil_tarefa', ['id'], unique=False)
    op.create_table('perfil_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_perfilusuario_usuario'),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], name='fk_perfilusuario_perfil'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_usuario_id'), 'perfil_usuario', ['id'], unique=False)
    op.create_table('usuario_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('dt_ultimoacesso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_usuariocliente_cliente'),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_usuariocliente_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_cliente_id'), 'usuario_cliente', ['id'], unique=False)
    op.create_table('automacao_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('automacao_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['automacao_id'], ['automacao.id'], name='fk_automacao_usuario_automacao'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_automacao_usuario_cliente'),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_automacao_usuario_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automacao_usuario_id'), 'automacao_usuario', ['id'], unique=False)
    op.create_table('download_worker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('automacao_id', sa.Integer(), nullable=True),
    sa.Column('nu_cpf', sa.String(length=11), nullable=True),
    sa.Column('tx_nome', sa.String(length=200), nullable=True),
    sa.Column('tx_ip_mac', sa.String(length=30), nullable=True),
    sa.Column('tx_ip', sa.String(length=30), nullable=True),
    sa.Column('tx_hostname', sa.String(length=200), nullable=True),
    sa.Column('tx_os', sa.String(length=200), nullable=True),
    sa.Column('tx_processador', sa.String(length=200), nullable=True),
    sa.Column('nu_cpu', sa.Integer(), nullable=True),
    sa.Column('tx_memoria', sa.String(length=10), nullable=True),
    sa.Column('tx_hd', sa.String(length=10), nullable=True),
    sa.Column('tx_hd_livre', sa.String(length=10), nullable=True),
    sa.Column('tx_diretorio', sa.String(length=500), nullable=True),
    sa.Column('dt_download', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dt_alive', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('tx_json', sa.Text(), nullable=True),
    sa.Column('bo_status', sa.Boolean(), server_default='t', nullable=True),
    sa.Column('bo_ativo', sa.Boolean(), server_default='t', nullable=True),
    sa.ForeignKeyConstraint(['automacao_id'], ['automacao.id'], name='fk_download_worker_automacao'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_download_worker_cliente'),
    sa.ForeignKeyConstraint(['nu_cpf'], ['usuario.nu_cpf'], name='fk_download_worker_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_worker_id'), 'download_worker', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_worker_id'), table_name='download_worker')
    op.drop_table('download_worker')
    op.drop_index(op.f('ix_automacao_usuario_id'), table_name='automacao_usuario')
    op.drop_table('automacao_usuario')
    op.drop_index(op.f('ix_usuario_cliente_id'), table_name='usuario_cliente')
    op.drop_table('usuario_cliente')
    op.drop_index(op.f('ix_perfil_usuario_id'), table_name='perfil_usuario')
    op.drop_table('perfil_usuario')
    op.drop_index(op.f('ix_perfil_tarefa_id'), table_name='perfil_tarefa')
    op.drop_table('perfil_tarefa')
    op.drop_index(op.f('ix_perfil_menu_id'), table_name='perfil_menu')
    op.drop_table('perfil_menu')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_dado_negocial_id'), table_name='dado_negocial')
    op.drop_table('dado_negocial')
    op.drop_index(op.f('ix_controle_execucao_id'), table_name='controle_execucao')
    op.drop_table('controle_execucao')
    op.drop_index(op.f('ix_cofre_senha_id'), table_name='cofre_senha')
    op.drop_table('cofre_senha')
    op.drop_index(op.f('ix_automacao_id'), table_name='automacao')
    op.drop_table('automacao')
    op.drop_index(op.f('ix_anexo_script_id'), table_name='anexo_script')
    op.drop_table('anexo_script')
    op.drop_index(op.f('ix_usuario_nu_cpf'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tarefa_historico_id'), table_name='tarefa_historico')
    op.drop_table('tarefa_historico')
    op.drop_index(op.f('ix_tarefa_id'), table_name='tarefa')
    op.drop_table('tarefa')
    op.drop_index(op.f('ix_perfil_id'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_menu_id'), table_name='menu')
    op.drop_table('menu')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
